name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: "contains(github.event.head_commit.message, '[deploy]') || (!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci'))"
        steps:
            - uses: actions/checkout@v2

            - name: Prepare repository
              run: git fetch --unshallow --tags

            - name: Use Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Build
              run: yarn build && yarn build-storybook

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./storybook-static
